//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;  &gt;
        ///&lt;channel&gt;
        ///	&lt;title&gt;Интересные / Публикации / Хабралента&lt;/title&gt;
        ///	&lt;link&gt;https://habrahabr.ru/feed/posts/&lt;/link&gt;
        ///	&lt;description&gt;&lt;![CDATA[Интересные публикации из Хабраленты]]&gt;&lt;/description&gt;
        ///	&lt;language&gt;ru&lt;/language&gt;
        ///	&lt;managingEditor&gt;editor@habrahabr.ru&lt;/managingEditor&gt;
        ///	&lt;generator&gt;habrahabr.ru&lt;/generator&gt;
        ///	&lt;pubDate&gt;Thu, 15 Dec 2016 19:42:38 GMT&lt;/pubDate&gt;
        ///	&lt;lastBuildDate&gt;&lt;/lastBuildDate&gt;
        ///        &lt;im [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RSSHabr {
            get {
                return ResourceManager.GetString("RSSHabr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;title&gt;Яндекс.Новости: Игры&lt;/title&gt;
        ///    &lt;link&gt;https://news.yandex.ru/games.html&lt;/link&gt;
        ///    &lt;description&gt;
        ///      Первая в России служба автоматической обработки и систематизации новостей. Сообщения ведущих российских и мировых СМИ. Обновление в режиме реального времени 24 часа в сутки.
        ///    &lt;/description&gt;
        ///    &lt;image&gt;
        ///      &lt;url&gt;https://company.yandex.ru/i/50x23.gif&lt;/url&gt;
        ///      &lt;link&gt;https://news.yandex.ru/games.html&lt;/link&gt;
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string RSSYandex {
            get {
                return ResourceManager.GetString("RSSYandex", resourceCulture);
            }
        }
    }
}
